In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('water_potability.csv')

In [3]:
dataset

ph    Hardness        Solids  Chloramines     Sulfate  \
0          NaN  204.890455  20791.318981     7.300212  368.516441   
1     3.716080  129.422921  18630.057858     6.635246         NaN   
2     8.099124  224.236259  19909.541732     9.275884         NaN   
3     8.316766  214.373394  22018.417441     8.059332  356.886136   
4     9.092223  181.101509  17978.986339     6.546600  310.135738   
...        ...         ...           ...          ...         ...   
3271  4.668102  193.681735  47580.991603     7.166639  359.948574   
3272  7.808856  193.553212  17329.802160     8.061362         NaN   
3273  9.419510  175.762646  33155.578218     7.350233         NaN   
3274  5.126763  230.603758  11983.869376     6.303357         NaN   
3275  7.874671  195.102299  17404.177061     7.509306         NaN   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       564.308654       10.379783        86.990970   2.963135           0  
1       592.885359       15.180013        56.329076   4.500656           0  
2       418.606213       16.868637        66.420093   3.055934           0  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
...            ...             ...              ...        ...         ...  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225              NaN   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459760       16.140368        78.698446   2.309149           1  

[3276 rows x 10 columns]

In [4]:
y = dataset.iloc[:,9].values
X = dataset.iloc[:,0:8].values

In [5]:
X

array([[           nan, 2.04890455e+02, 2.07913190e+04, ...,
        5.64308654e+02, 1.03797831e+01, 8.69909705e+01],
       [3.71608008e+00, 1.29422921e+02, 1.86300579e+04, ...,
        5.92885359e+02, 1.51800131e+01, 5.63290763e+01],
       [8.09912419e+00, 2.24236259e+02, 1.99095417e+04, ...,
        4.18606213e+02, 1.68686369e+01, 6.64200925e+01],
       ...,
       [9.41951032e+00, 1.75762646e+02, 3.31555782e+04, ...,
        4.32044783e+02, 1.10390697e+01, 6.98454003e+01],
       [5.12676292e+00, 2.30603758e+02, 1.19838694e+04, ...,
        4.02883113e+02, 1.11689462e+01, 7.74882131e+01],
       [7.87467136e+00, 1.95102299e+02, 1.74041771e+04, ...,
        3.27459760e+02, 1.61403676e+01, 7.86984463e+01]])

In [6]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 22)

In [8]:
X_train

array([[5.04140503e+00, 1.93167853e+02, 1.73423141e+04, ...,
        4.44453496e+02, 1.74727885e+01, 6.65421980e+01],
       [8.31595907e+00, 2.21270223e+02, 1.61233045e+04, ...,
        5.01673983e+02, 2.21597472e+01, 7.53649741e+01],
       [6.79083820e+00, 2.71601212e+02, 1.43485729e+04, ...,
        6.10629550e+02, 9.38679889e+00, 9.14021117e+01],
       ...,
       [9.48583287e+00, 2.18738236e+02, 1.53578334e+04, ...,
        4.29622212e+02, 1.56211387e+01, 6.48260282e+01],
       [5.18941367e+00, 1.71238926e+02, 1.22899009e+04, ...,
        5.01559725e+02, 1.22843335e+01, 5.44739346e+01],
       [           nan, 2.00661925e+02, 2.95138049e+04, ...,
        4.76201585e+02, 1.99500538e+01,            nan]])

In [9]:
X_test

array([[           nan, 1.97712183e+02, 1.29623897e+04, ...,
        5.03843001e+02, 1.88923935e+01, 8.03463478e+01],
       [7.52898041e+00, 2.25340986e+02, 8.12973492e+03, ...,
        3.79339293e+02, 1.69619444e+01, 6.42657872e+01],
       [5.62633953e+00, 2.30857983e+02, 1.44424189e+04, ...,
        3.46553206e+02, 1.13687024e+01, 4.31951816e+01],
       ...,
       [6.43644450e+00, 1.92995665e+02, 1.95793895e+04, ...,
        3.79675367e+02, 1.28970493e+01, 7.58391318e+01],
       [6.72463934e+00, 2.23175415e+02, 4.15520197e+04, ...,
        4.63885216e+02, 1.31650346e+01, 6.10587957e+01],
       [9.03832607e+00, 2.27357659e+02, 3.43538397e+04, ...,
        4.21664482e+02, 1.63314215e+01, 9.26433826e+01]])

In [10]:
y_train

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [11]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,